### PR TITLE
Added gitignore file and remove intellij idea conf files.

### PR DESCRIPTION
**Pull request by kagawish**
Testing the pull request workflow.

### CODE REVIEW

**Comment by mohannadGen** [comment]
why you deleted placeholder for the list of songs

**Comment by kagawish** [comment]
I didn't

**Comment by mohannadGen** [comment]
ok i'll merge it

**Comment by kagawish** [comment]
Ok, Thank you :)

**Comment by kagawish** [comment]
Sorry I am just getting used to the new workflow, so there maybe some errors at the beginning :)

**Comment by mohannadGen** [comment]
no problem

**Comment by kagawish** [comment]
Why didn't you merge the pull request?

**Comment by mohannadGen** [comment]
i merged it , but it is also my first time using this work flow

**Comment by kagawish** [comment]
Oki :+1:

**Pull request closed without merging**
