### PR TITLE
Added gitignore file and remove intellij idea conf files.

### PR DESCRIPTION
**Pull request by kagawish**

### CODE REVIEW

**Comment by mohannadGen** [comment]
I did it

**Comment by kagawish** [comment]
Ah yes, I think it worked :+1:

**Comment by mohannadGen** [comment]
yes but it is complicated

**Comment by kagawish** [comment]
However, I see still the .idea folder in your repository, why is this?

**Comment by kagawish** [comment]
As a final thing, just remove this folder and the file it contains.

**Comment by mohannadGen** [comment]
I should have used "git add --all" instead of " commit -a -m "" "
usually in this work flow we do pull request after adding new feature so, you can do it once by day,

**Comment by mohannadGen** [comment]
do it again

**Comment by kagawish** [comment]
ok

**Comment by kagawish** [comment]
I can't because, you integrated ever change I made already within the last merge, you just have to remove it from your repository and push changes.

**Comment by mohannadGen** [comment]
I removed it , it is not in my local repo any more ,,, i don't know why it is still in remote repo !!!!!
no problem ,,, we don't have to wast our time in this things

**Comment by mohannadGen** [comment]
ok i did it ,,  it was a hidden folder :-)

**Comment by mohannadGen** [comment]
good night

**Comment by kagawish** [comment]
Good night :+1: :+1:

**Pull request merged**
